#if !defined(AFX_AGENTCTLPROPERTYSHEET_H__BD82255F_EB8C_413C_85A6_B2A4463F159F__INCLUDED_)
#define AFX_AGENTCTLPROPERTYSHEET_H__BD82255F_EB8C_413C_85A6_B2A4463F159F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlPropertySheet wrapper class

class CAgentCtlPropertySheet : public COleDispatchDriver
{
public:
	CAgentCtlPropertySheet() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlPropertySheet(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlPropertySheet(const CAgentCtlPropertySheet& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetLeft();
	short GetTop();
	short GetHeight();
	short GetWidth();
	void SetVisible(BOOL bNewValue);
	BOOL GetVisible();
	void SetPage(LPCTSTR lpszNewValue);
	CString GetPage();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLPROPERTYSHEET_H__BD82255F_EB8C_413C_85A6_B2A4463F159F__INCLUDED_)
