#if !defined(AFX_AGENTCTLCHARACTERS_H__761993B0_E199_4BC6_AA5C_75AC984CE5EC__INCLUDED_)
#define AFX_AGENTCTLCHARACTERS_H__761993B0_E199_4BC6_AA5C_75AC984CE5EC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAgentCtlCharacterEx;
class CAgentCtlRequest;

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlCharacters wrapper class

class CAgentCtlCharacters : public COleDispatchDriver
{
public:
	CAgentCtlCharacters() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlCharacters(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlCharacters(const CAgentCtlCharacters& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAgentCtlCharacterEx GetItem(LPCTSTR CharacterID);
	CAgentCtlCharacterEx Character(LPCTSTR CharacterID);
	void Unload(LPCTSTR CharacterID);
	CAgentCtlRequest Load(LPCTSTR CharacterID, const VARIANT& LoadKey);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLCHARACTERS_H__761993B0_E199_4BC6_AA5C_75AC984CE5EC__INCLUDED_)
