#if !defined(AFX_AGENTCTLCOMMANDSWINDOW_H__D5E95629_0BDC_4CCD_84FE_F8E50AE908E5__INCLUDED_)
#define AFX_AGENTCTLCOMMANDSWINDOW_H__D5E95629_0BDC_4CCD_84FE_F8E50AE908E5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlCommandsWindow wrapper class

class CAgentCtlCommandsWindow : public COleDispatchDriver
{
public:
	CAgentCtlCommandsWindow() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlCommandsWindow(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlCommandsWindow(const CAgentCtlCommandsWindow& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	short GetLeft();
	short GetTop();
	short GetHeight();
	short GetWidth();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLCOMMANDSWINDOW_H__D5E95629_0BDC_4CCD_84FE_F8E50AE908E5__INCLUDED_)
