#if !defined(AFX_AGENTCTLREQUEST_H__9B717FC8_044E_4124_A470_43C6CBC751DA__INCLUDED_)
#define AFX_AGENTCTLREQUEST_H__9B717FC8_044E_4124_A470_43C6CBC751DA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlRequest wrapper class

class CAgentCtlRequest : public COleDispatchDriver
{
public:
	CAgentCtlRequest() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlRequest(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlRequest(const CAgentCtlRequest& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStatus();
	CString GetDescription();
	long GetNumber();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLREQUEST_H__9B717FC8_044E_4124_A470_43C6CBC751DA__INCLUDED_)
