// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "agentctlaudioobjectex.h"


/////////////////////////////////////////////////////////////////////////////
// CAgentCtlAudioObjectEx properties

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlAudioObjectEx operations

BOOL CAgentCtlAudioObjectEx::GetEnabled()
{
	BOOL result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CAgentCtlAudioObjectEx::GetSoundEffects()
{
	BOOL result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

short CAgentCtlAudioObjectEx::GetStatus()
{
	short result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}
