#if !defined(AFX_AGENTCTLANIMATIONNAMES_H__A398DBA5_80EC_47C2_85A2_D320E93E0649__INCLUDED_)
#define AFX_AGENTCTLANIMATIONNAMES_H__A398DBA5_80EC_47C2_85A2_D320E93E0649__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlAnimationNames wrapper class

class CAgentCtlAnimationNames : public COleDispatchDriver
{
public:
	CAgentCtlAnimationNames() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlAnimationNames(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlAnimationNames(const CAgentCtlAnimationNames& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLANIMATIONNAMES_H__A398DBA5_80EC_47C2_85A2_D320E93E0649__INCLUDED_)
