#if !defined(AFX_AGENTCTLCOMMAND_H__1572ED52_D40E_4F68_B329_8C9DDB424DD5__INCLUDED_)
#define AFX_AGENTCTLCOMMAND_H__1572ED52_D40E_4F68_B329_8C9DDB424DD5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlCommand wrapper class

class CAgentCtlCommand : public COleDispatchDriver
{
public:
	CAgentCtlCommand() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlCommand(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlCommand(const CAgentCtlCommand& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetVoice();
	void SetVoice(LPCTSTR lpszNewValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetConfidence();
	void SetConfidence(long nNewValue);
	CString GetConfidenceText();
	void SetConfidenceText(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLCOMMAND_H__1572ED52_D40E_4F68_B329_8C9DDB424DD5__INCLUDED_)
