#if !defined(AFX_AGENTCTLBALLOONEX_H__66E3737E_2C78_40CC_9E27_2F4C87BA6878__INCLUDED_)
#define AFX_AGENTCTLBALLOONEX_H__66E3737E_2C78_40CC_9E27_2F4C87BA6878__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlBalloonEx wrapper class

class CAgentCtlBalloonEx : public COleDispatchDriver
{
public:
	CAgentCtlBalloonEx() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlBalloonEx(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlBalloonEx(const CAgentCtlBalloonEx& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	long GetNumberOfLines();
	long GetCharsPerLine();
	CString GetFontName();
	long GetFontSize();
	BOOL GetFontBold();
	BOOL GetFontItalic();
	BOOL GetFontStrikethru();
	BOOL GetFontUnderline();
	long GetForeColor();
	long GetBackColor();
	long GetBorderColor();
	void SetVisible(BOOL bNewValue);
	BOOL GetVisible();
	void SetFontName(LPCTSTR lpszNewValue);
	void SetFontSize(long nNewValue);
	void SetFontCharSet(short nNewValue);
	short GetFontCharSet();
	void SetStyle(long nNewValue);
	long GetStyle();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLBALLOONEX_H__66E3737E_2C78_40CC_9E27_2F4C87BA6878__INCLUDED_)
