#if !defined(AFX_AGENTCTLCOMMANDSEX_H__AEEBDFBD_9095_458F_8923_2908E8CA696F__INCLUDED_)
#define AFX_AGENTCTLCOMMANDSEX_H__AEEBDFBD_9095_458F_8923_2908E8CA696F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAgentCtlCommandEx;
class CAgentCtlCommand;

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlCommandsEx wrapper class

class CAgentCtlCommandsEx : public COleDispatchDriver
{
public:
	CAgentCtlCommandsEx() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlCommandsEx(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlCommandsEx(const CAgentCtlCommandsEx& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAgentCtlCommandEx GetItem(LPCTSTR Name);
	CAgentCtlCommandEx Command(LPCTSTR Name);
	long GetCount();
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	CString GetVoice();
	void SetVoice(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CAgentCtlCommand Add(LPCTSTR Name, const VARIANT& Caption, const VARIANT& Voice, const VARIANT& Enabled, const VARIANT& Visible);
	CAgentCtlCommand Insert(LPCTSTR Name, LPCTSTR RefName, const VARIANT& Before, const VARIANT& Caption, const VARIANT& Voice, const VARIANT& Enabled, const VARIANT& Visible);
	void Remove(LPCTSTR Name);
	void RemoveAll();
	void SetDefaultCommand(LPCTSTR lpszNewValue);
	CString GetDefaultCommand();
	void SetHelpContextID(long nNewValue);
	long GetHelpContextID();
	void SetFontName(LPCTSTR lpszNewValue);
	CString GetFontName();
	long GetFontSize();
	void SetFontSize(long nNewValue);
	void SetVoiceCaption(LPCTSTR lpszNewValue);
	CString GetVoiceCaption();
	void SetGlobalVoiceCommandsEnabled(BOOL bNewValue);
	BOOL GetGlobalVoiceCommandsEnabled();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLCOMMANDSEX_H__AEEBDFBD_9095_458F_8923_2908E8CA696F__INCLUDED_)
