//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MJAntiVirus.rc
//
#define IDD_MJANTIVIRUS_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_DLG_SCANSET                 107
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       136
#define IDI_ICON2                       137
#define IDI_ICON3                       138
#define IDI_ICON4                       139
#define IDI_ICON5                       140
#define IDI_ICON6                       141
#define IDI_ICON7                       142
#define IDI_ICON_CDROM                  144
#define IDI_ICON_DOCUMENT               145
#define IDI_ICON_HARDDISK               146
#define IDI_ICON_MEMORY                 147
#define IDI_ICON_MYCOMPUTER             148
#define IDI_ICON_SYSFILE                149
#define IDI_ICON_USB                    150
#define IDD_PROP1                       151
#define IDD_PROP2                       152
#define IDD_PROP3                       153
#define IDD_DLG_COMPUTERINFO            154
#define IDD_LOCK_DLG                    155
#define IDD_DLG_SETPASSWORD             156
#define IDD_DLG_LOCKORSET               157
#define IDD_DLG_MONITORFILE             158
#define IDD_FILEENCRY_DIALOG            159
#define IDD_FOLDERENCRY_DIALOG          160
#define IDD_ABOUT_DIALOG                162
#define IDB_BITMAP1                     166
#define IDR_TRAYMENU                    167
#define IDB_LEFTBITMAP                  168
#define IDB_ITEMBITMAP                  169
#define IDD_DLG_NETMONI                 170
#define IDD_DLG_REG                     171
#define IDB_BITMAP2                     173
#define IDD_DLG_SCREENPROTECT           174
#define IDB_BITMAP3                     175
#define IDB_BITMAP4                     176
#define IDB_BITMAP5                     177
#define IDB_BITMAP6                     178
#define IDB_BITMAP7                     179
#define IDC_TRDISKTREE                  1002
#define IDC_BTN_START                   1003
#define IDC_LB_SHOWF                    1004
#define IDC_BTN_PAUSE                   1005
#define IDC_BTN_STOP                    1006
#define IDC_EDIT_TIME                   1007
#define IDC_LIST_SHOWRLT                1009
#define IDC_LB_FILENUM                  1012
#define IDC_RADIO_MEMFIRST              1013
#define IDC_RADIO_UNMEMFIRST            1014
#define IDC_RADIO_DERDEL                1015
#define IDC_RADIO_KILLDEL               1016
#define IDC_RADIO_KILLNOTE              1017
#define IDC_RADIO_DERNOTE               1018
#define IDC_RADIO_ALLFILE               1019
#define IDC_RADIO_EXEFILE               1020
#define IDC_RADIO_HIGHSPEED             1021
#define IDC_RADIO_MIDSPEED              1022
#define IDC_RADIO_LOWSPEED              1023
#define IDC_RADIO_TURNOFFAFT            1024
#define IDC_RADIO_NONTURNOFF            1025
#define IDC_BTN_SCANSETOK               1026
#define IDC_BTN_SCANSETCANCEL           1027
#define IDC_LIST_SELEICON               1028
#define IDC_PROP3_CHECK1                1029
#define IDC_PROP3_CHECK2                1030
#define IDC_PROP3_CHECK3                1031
#define IDC_EDIT_COMPUTERNAME           1032
#define IDC_PROP3_CHECK4                1032
#define IDC_EDIT_CPTINFO1               1032
#define IDC_PROP2_CHECK5                1033
#define IDC_EDIT_CPTINFO2               1033
#define IDC_PROP1_CHECK1                1034
#define IDC_PROP2_CHECK6                1034
#define IDC_EDIT_CPTINFO3               1034
#define IDC_PROP1_CHECK2                1035
#define IDC_EDIT_CPTINFO4               1035
#define IDC_PROP1_CHECK3                1036
#define IDC_EDIT_CPTINFO5               1036
#define IDC_PROP1_CHECK4                1037
#define IDC_EDIT_CPTINFO6               1037
#define IDC_PROP1_CHECK5                1038
#define IDC_EDIT_CPTINFO7               1038
#define IDC_PROP2_CHECK1                1039
#define IDC_EDIT_CPTINFO8               1039
#define IDC_PROP2_CHECK2                1040
#define IDC_PROP2_CHECK3                1041
#define IDC_PROP2_CHECK4                1042
#define IDC_LOCK_EDIT1                  1043
#define IDC_LOCK_BTN1                   1044
#define IDC_EDIT1                       1045
#define IDC_LOCK_BTN_SCREEN             1045
#define IDC_BUTTON1                     1046
#define IDC_BTN_LOCKCPT                 1047
#define IDC_STOP                        1047
#define IDC_BTENCRY                     1047
#define IDC_BTN_CANCEL                  1047
#define IDC_BTN_SETCODE                 1048
#define IDC_CLEAR                       1048
#define IDC_BTUNENCRY                   1048
#define IDC_LIST1                       1051
#define IDC_START                       1052
#define IDC_STATE                       1053
#define IDC_EDBODY                      1054
#define IDC_BTOPEN                      1055
#define IDC_FILEPATH                    1057
#define ID_ADD                          1060
#define IDC_EDDIR                       1061
#define IDC_LABEL1                      1063
#define IDC_LABEL2                      1064
#define IDC_LABEL3                      1065
#define IDC_LABEL4                      1066
#define IDC_LABEL5                      1067
#define IDC_LABEL6                      1068
#define IDC_BTN_BEGINLISTEN             1069
#define IDC_EDIT_REGCODE                1070
#define IDC_BTN_REG                     1071
#define IDC_BTN_QUITREG                 1072
#define IDC_LAB_REGSTATE                1073
#define IDC_INITUI                      1074
#define IDC_AGENT1                      1075
#define IDC_LIST_OUTLOOK                1555
#define IDC_SETDLG_BTN_OK               1600
#define IDC_SETDLG_BTN_CANCEL           1601
#define WM_TRARMESSAGE                  32005
#define ID_MENUITEM_RESTORE             32775
#define ID_MENUITEM_CLOSE               32776
#define ID_MENUITEM_CMPINFO             32777
#define ID_MENUITEM_LOCK                32778
#define ID_MENUITEM_SYSMONI             32779
#define ID_MENUITEM_NETMONI             32780
#define ID_MENUITEM_REGISTER            32782
#define ID_MENUITEM_ABOUT               32783
#define ID_MENUITEM_SHOWPROC            32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
